name: Afficher des messages

on:
  push:
    branches:
      - '**' # Déclenche l'action sur n'importe quelle branche lors d'un push
  pull_request:
    branches:
      - '**' 

jobs:
  afficher-message:
    runs-on: ubuntu-latest

    steps:
      # Étape pour afficher un message lors d'un push
      - name: Afficher un message pour un push
        if: github.event_name == 'push'
        run: echo "Nouvelle poussée de code sur la branche ${GITHUB_REF##*/}"

      # Étape pour afficher un message lors d'une pull request
      - name: Afficher un message pour une pull request
        if: github.event_name == 'pull_request'
        run: echo "Besoin de vérification des codes"
